= Mold - Workshop

A workshop in web development: creating a website where users can upload
images, manipulate them, and download the result.

In doing so, the following concepts are introduced:

* Typescript, HTML, and CSS
* Event-based and asynchronous programming
** Dealing with HTML5 forms
** Uploading and reading files
* NPM
** Importing, bundling, and using external libraries

The starter code is provided in `/starter`.

See https://github.com/Dophin2009/mold for the completed source code and
https://dophin2009.github.io/mold for a deployed instance.

== Building

Requirements for main document (if not using Docker):

* Python 3.6+
** Alternatively, a TeX installation (see link:packages.txt[`packages.txt`] for
   list of extra required packages)

See https://github.com/Dophin2009/mold for instructions on building the actual
project.

=== Unix

To build on Unix/Linux/macOS without a TeX installation:

[source,shell]
----
./install.py install
. local/activate
latexmk                       # or: make index
                              # build should be at target/index.pdf

deactivate                    # when leaving the project directory
----

With a TeX installation:

[source,shell]
----
tlmgr install $(cat packages) # if missing any required packages
latexmk                       # or: make index
----

=== Windows

To build on Windows without a TeX installation (not tested):

[source,powershell]
----
python3 install.py install
. local/activate.ps1
latexmk                       # or: make index
                              # build should be at target/index.pdf

deactivate                    # when leaving the project directory
----

With a TeX installation:

[source,shell]
----
# install any missing packages specified in packages.txt
latexmk                       # or: make index
----

=== Docker

To build with Docker:

[source,shell]
----
DOCKER_BUILDKIT=1 docker build --output target .  # build should be at target/index.pdf
----

== License

This project is licensed under the MIT license. See link:LICENSE.txt[LICENSE.txt] for
more details.
